### ISSUE TITLE
[Feature Request]: Error middleware

### ISSUE THREAD

**Issue by Somfic** [KaanMol/CalendarServer#6]
### Problem Description

Currently the API does not implement any middleware for the handling of any errors that may occur. This is inconsistent compared to the rest of the API. Now the API returns a status 400 `text/plain` body with a vague error description.

For example, calling `/sources` with the following body
```json
{ 
	this is json (trust me bro)
}
```
results in the following response
```
Json deserialize error: expected ident at line 1 column 2
```

### Proposed Solution

Make the API return a consistently formatted error body, for example:

```json
{
    "success": false,
    "error": {
        "code": 400,
        "message": "Json deserialize error: expected ident at line 1 column 2"
    },
    "data": null
}
```

### Alternatives Considered

n/a

**Comment by KaanMol** [comment]
I agree that this is an issue, and we should make a PR for this. Returning the actual deserialize error might not be the best idea, as proposed in your solution. A generic `Invalid body` error message would be more appropriate. 

Who of us would you like to make a PR for this?
